// eslint-disable-next-line import/no-anonymous-default-export
export default {
  cms_manual_init: true,
  backend: {
    name: "git-gateway",
    repo: "elbec-group/elbec.group",
    branch: "main",
    publish_mode: "editorial_workflow",
  },
  local_backend: true,
  media_folder: "images/media",
  public_folder: "images",
  slug: {
    encoding: "ascii",
    clean_accents: true,
    sanitize_replacement: "_",
  },
  i18n: {
    structure: "multiple_folders",
    locales: ["en", "es", "ca"],
    default_locale: "en",
  },
  collections: [
    {
      name: "pages",
      label: "Pages",
      files: [
        {
          name: "home",
          label: "Home English",
          file: "content/pages/en/home.md",
          fields: [
            {
              name: "hero_title",
              label: "[en] Hero Title",
              widget: "string",
            },
            {
              name: "logo_alt",
              label: "[en] Logo Alt Text",
              widget: "string",
            },
            {
              name: "home_title",
              label: "[en] Home Title",
              widget: "string",
            },
            {
              name: "num_news",
              label: "[en] Number of news & events",
              widget: "number",
              default: 2,
              value_type: "int",
              min: 1,
              max: 4,
              step: 1,
            },
            {
              name: "num_projects",
              label: "[en] Number of projects",
              widget: "number",
              default: 2,
              value_type: "int",
              min: 1,
              max: 4,
              step: 1,
            },
          ],
        },
        {
          name: "home-es",
          label: "Home Spanish",
          file: "content/pages/es/home.md",
          fields: [
            {
              name: "hero_title",
              label: "[es] Hero Title",
              widget: "markdown",
            },
            {
              name: "logo_alt",
              label: "[es] Logo Alt Text",
              widget: "string",
            },
          ],
        },
        {
          name: "home-ca",
          label: "Home Catalan",
          file: "content/pages/ca/home.md",
          fields: [
            {
              name: "hero_title",
              label: "[ca] Hero Title",
              widget: "markdown",
            },
            {
              name: "logo_alt",
              label: "[ca] Logo Alt Text",
              widget: "string",
            },
          ],
        },
      ],
    },
    {
      name: "authors",
      label: "Authors / Members",
      folder: "content/authors",
      identifier_field: "name",
      create: true,
      fields: [
        {
          label: "Name",
          name: "name",
          widget: "string",
        },
        {
          label: "Photo",
          name: "photo",
          widget: "image",
          required: false,
        },
        {
          label: "Role",
          name: "role",
          widget: "string",
          required: false,
        },
        {
          label: "Link",
          name: "url",
          widget: "string",
          required: false,
        },
        {
          label: "Biography",
          name: "bio",
          widget: "markdown",
          required: false,
        },
      ],
    },
    {
      name: "publication_type",
      label: "Publication Type",
      folder: "content/publication_type",
      identifier_field: "name",
      create: true,
      fields: [
        {
          label: "Name",
          name: "name",
          widget: "string",
        },
      ],
    },
    {
      name: "projects",
      label: "Projects",
      label_singular: "Project",
      i18n: true,
      folder: "content/projects",
      identifier_field: "name",
      create: true,
      fields: [
        {
          label: "Is Publish",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        },
        {
          label: "ID",
          name: "id",
          widget: "string",
        },
        {
          label: "Publication Date",
          name: "publication_date",
          widget: "date",
        },
        {
          label: "Name",
          name: "name",
          widget: "string",
          i18n: true,
        },
        {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
        },
        {
          label: "Reference",
          name: "reference",
          widget: "string",
        },
        {
          label: "Funding agency",
          name: "funding_agency",
          widget: "string",
        },
        {
          label: "Amount",
          name: "amout",
          widget: "string",
        },
        {
          label: "Running from",
          name: "running_from",
          widget: "string",
        },
        {
          label: "PI",
          collection: "authors",
          name: "pi",
          multiple: true,
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
        {
          label: "Abstract",
          name: "abstract",
          widget: "markdown",
          i18n: true,
        },
        {
          label: "Relevant outputs",
          name: "relevant_outputs",
          widget: "string",
          required: false,
        },
        {
          label: "Members",
          collection: "authors",
          multiple: true,
          name: "members",
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
      ],
    },
    {
      name: "publications",
      label: "Publications",
      label_singular: "Publication",
      i18n: true,
      folder: "content/publications",
      identifier_field: "title",
      create: true,
      fields: [
        {
          label: "Publication Type",
          collection: "publication_type",
          multiple: false,
          name: "publication_type",
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
        {
          label: "Eds.",
          name: "eds",
          widget: "string",
        },
        {
          label: "Title",
          name: "title",
          widget: "string",
          i18n: true,
        },
        {
          label: "Journal",
          name: "journal",
          widget: "string",
        },
        {
          label: "Publishing house",
          name: "publishing_house",
          widget: "string",
        },
        {
          label: "Year",
          name: "year",
          widget: "string",
        },
        {
          label: "DOI/Link (insert the URL)",
          name: "doi",
          widget: "string",
        },
        {
          label: "Abstract",
          name: "abstract",
          widget: "markdown",
          i18n: true,
        },
        {
          label: "Authors",
          collection: "authors",
          multiple: true,
          name: "authors",
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
        {
          label: "Elbec members involved",
          collection: "authors",
          multiple: true,
          name: "elbec_members_involved",
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
        {
          label: "Project",
          collection: "projects",
          multiple: true,
          name: "projects",
          search_fields: ["name"],
          value_field: "name",
          widget: "relation",
        },
      ],
    },
  ],
};
